from __future__ import annotations

from abc import ABC
from dataclasses import dataclass

from krrood.exceptions import DataclassException


class DontPrintStackTrace:
    """
    Marker mixin for exceptions whose stack trace should not be printed.
    """


@dataclass
class GiskardException(DataclassException):
    """
    Base class for all errors raised by Giskard.
    """


@dataclass
class MotionFailure(GiskardException, ABC):
    """
    Raised when a motion cannot be carried out: it runs out of ticks, the controller
    cannot satisfy its constraints, or moving there would hit something.

    None of these say the plan is wrong, only that this way of carrying it out is, so a
    step with other candidates on offer is free to try the next one.
    """


@dataclass
class MotionTimeout(MotionFailure, TimeoutError):
    """
    Raised when a motion has not ended within the ticks it was given.
    """

    tick_budget: int
    """
    How many ticks the motion was allowed to take.
    """

    def error_message(self) -> str:
        return f"Motion did not end within {self.tick_budget} ticks."

    def suggest_correction(self) -> str:
        return ""


@dataclass
class SetupException(GiskardException):
    """
    Base class for errors that occur while configuring Giskard.
    """


@dataclass
class PlanningException(GiskardException):
    """
    Base class for errors that occur while planning a motion.
    """


@dataclass
class MissingActionResultError(GiskardException):
    """
    Raised when a result message is requested before one has been set.
    """

    action_server_name: str
    """
    The name of the action server whose result was requested.
    """

    goal_id: int
    """
    The id of the goal whose result was requested.
    """

    def error_message(self) -> str:
        return (
            f"'{self.action_server_name}' goal #{self.goal_id} has no result message."
        )

    def suggest_correction(self) -> str:
        return "You tried to access something before it was set."


@dataclass
class MissingGoalOutcomeError(GiskardException):
    """
    Raised when a goal is answered without having been marked succeeded, aborted or
    canceled.
    """

    action_server_name: str
    """
    The name of the action server whose goal is being answered.
    """

    goal_id: int
    """
    The id of the goal that is being answered.
    """

    def error_message(self) -> str:
        return (
            f"'{self.action_server_name}' goal #{self.goal_id} is being answered "
            f"without an outcome."
        )

    def suggest_correction(self) -> str:
        return (
            "Mark the goal as succeeded, aborted or canceled before sending its result."
        )


@dataclass
class DuplicateNameException(GiskardException):
    """
    Raised when a name that must be unique is used more than once.
    """

    name: str
    """
    The name that already exists.
    """

    def error_message(self) -> str:
        return f'A constraint named "{self.name}" already exists.'

    def suggest_correction(self) -> str:
        return "Node names of Motion Statecharts are autogenerated. You are likely setting names manually. Don't do that if you don't care about names."


@dataclass
class NoControlledJointsError(SetupException):
    """
    Raised when no joint is flagged as controlled.
    """

    def error_message(self) -> str:
        return "No joints are flagged as controlled."

    def suggest_correction(self) -> str:
        return "Make sure robot_interface_config of Giskard is setup correctly."


@dataclass
class NonPositiveRealTimeFactorError(SetupException):
    """
    Raised when a simulation is configured to run at a non positive speed.
    """

    real_time_factor: float
    """
    The rejected factor.
    """

    def error_message(self) -> str:
        return f"A real time factor of {self.real_time_factor} would never advance the simulation."

    def suggest_correction(self) -> str:
        return "Use a positive factor, or NoPacing to run as fast as possible."


@dataclass
class JointRegistrationRequiresStandaloneModeError(SetupException):
    """
    Raised when joints are registered outside of StandAlone mode.
    """

    def error_message(self) -> str:
        return "Joints only need to be registered in StandAlone mode."

    def suggest_correction(self) -> str:
        return "Remove the manual registration. For real robots, the joints are retrieved from the connected controllers."


@dataclass
class MaxTrajectoryLengthException(PlanningException):
    """
    Raised when a planned trajectory exceeds the maximum allowed length.
    """

    def error_message(self) -> str:
        return "Trajectory exceeded the maximum allowed length."

    def suggest_correction(self) -> str:
        return "Look at the final state of the MotionStatechart to see which nodes are still running. Use the debugger or the MotionStatechart.draw() method to visualize the MotionStatechart."


@dataclass
class SelfCollisionViolatedException(PlanningException):
    """
    Raised when a self-collision constraint is violated during planning.
    """

    def error_message(self) -> str:
        return "A self-collision constraint was violated during planning."

    def suggest_correction(self) -> str:
        return ""
