"""
The Garmi collecting four machine parts from two storage racks onto a delivery rack.

Grown out of a Plan Builder demo: the carrying is spelled out as navigate / pick / place
rather than a TransportAction, because warehouse6 is a single hall mesh with no
navigable floor for a transport's costmap to search.

Every surface used here is one measured off ``warehouse6.glb`` itself, so the parts rest
on the hall's own shelving rather than on furniture spawned beside it. The parts differ
in shape, and so do the grasps: which face the hand closes on is what decides whether a
part fits between the fingers at all.

The screw box keeps the size of ``milk.stl``, so poses captured for that one still fit;
it is generated by ``scripts/make_transport_box_mesh.py``.
"""

from __future__ import annotations

import math
import os
from dataclasses import dataclass
from enum import StrEnum

from coraplex.datastructures.dataclasses import Context
from coraplex.datastructures.enums import (
    ApproachDirection,
    Arms,
    VerticalAlignment,
    VisualizationBackend,
)
from coraplex.datastructures.grasp import GraspDescription
from coraplex.demonstrations import RobotDemonstration
from coraplex.plans.factories import sequential
from coraplex.plans.plan_node import PlanNode
from coraplex.robot_plans.actions.core.navigation import NavigateAction
from coraplex.robot_plans.actions.core.pick_up import PickUpAction
from coraplex.robot_plans.actions.core.placing import PlaceAction
from coraplex.robot_plans.actions.core.robot_body import ParkArmsAction, MoveTorsoAction
from coraplex.view_manager import ViewManager
from semantic_digital_twin.api import (
    BodySpecification,
    Connection6DoFSpecification,
    RobotSpecification,
    SemanticAnnotationWithRootSpecification,
    WorldSpecification,
)
from semantic_digital_twin.datastructures.definitions import TorsoState
from semantic_digital_twin.reasoning.world_reasoner import WorldReasoner
from semantic_digital_twin.robots.garmi import Garmi
from semantic_digital_twin.robots.robot_part_mixins import HasMobileBase
from semantic_digital_twin.robots.robot_parts import EndEffector
from semantic_digital_twin.semantic_annotations.mixins import HasRootBody
from semantic_digital_twin.spatial_types import HomogeneousTransformationMatrix
from semantic_digital_twin.spatial_types.spatial_types import Pose
from semantic_digital_twin.world import World
from semantic_digital_twin.world_description.geometry import Color

_HERE = os.path.dirname(__file__)
_WORLDS = os.path.join(_HERE, "..", "..", "resources", "worlds")
_OBJECTS = os.path.join(_HERE, "..", "..", "resources", "objects")

ENV_FILE = "warehouse6.urdf"
ROBOT_XY = (1.5, 2.5)

BASE_MAY_DRIVE_WHILE_REACHING = False
"""
Whether the base may drive to help an arm reach (whole-body control).

Off, because every base pose in this plan is one that was captured deliberately: with it
on, a reach drives the base past the object and into the shelving.
"""

CARRYING_ARM = Arms.LEFT
"""
The arm that picks and places, one hand throughout.
"""

AVOIDS_COLLISIONS = True
"""
Whether every motion of the run carries a collision-avoidance goal.

On, because the hall is collided with: the racks the arm reaches into are geometry the
motions have to be held off, not just scenery the captured poses happen to miss.
"""

LYING_ON_ITS_SIDE = math.pi / 2
"""
Roll that tips a part off its own z-axis onto that axis' side.

It lays the axle down across the shelf front, and stands the plate on its rim.
"""

# %% the parts and where they belong


class PartMesh(StrEnum):
    """
    Mesh file of each part that is collected, which is also the body's name in the
    world.
    """

    SCREW_BOX = "screw_box.obj"
    WRENCH = "wrench.stl"
    AXLE = "axle.stl"
    PLATE = "plate.stl"


@dataclass(frozen=True)
class Part:
    """
    One part of the collection: what it is, where it lies, where it goes, and how the
    hand has to be turned to take hold of it.
    """

    mesh: PartMesh
    """
    The mesh the part is made of.
    """

    color: Color
    """
    What the part is painted, since an STL carries no color of its own.
    """

    storage_pose: Pose
    """
    Where the part lies on the storage rack at the start of the run.
    """

    storage_stand: Pose
    """
    Base pose the robot reaches :attr:`storage_pose` from.
    """

    delivery_pose: Pose
    """
    Where the part is put down on the delivery rack.
    """

    delivery_stand: Pose
    """
    Base pose the robot reaches :attr:`delivery_pose` from.
    """

    approach_direction: ApproachDirection
    """
    The side of the part the hand comes in from, in the part's own frame.
    """

    vertical_alignment: VerticalAlignment
    """
    Whether the hand comes down onto the part from above rather than in level with it.
    """

    rotate_gripper: bool
    """
    Whether the hand is rolled a quarter turn about its approach axis, which swaps the
    two faces the fingers can close on.
    """

    def grasp(self, end_effector: EndEffector) -> GraspDescription:
        """
        How this part is taken hold of.

        :param end_effector: The hand doing the grasping.
        """
        return GraspDescription(
            self.approach_direction,
            self.vertical_alignment,
            end_effector,
            rotate_gripper=self.rotate_gripper,
        )


PARTS = (
    Part(
        mesh=PartMesh.SCREW_BOX,
        color=Color(),
        storage_pose=Pose.from_xyz_rpy(2.35, -0.05, 0.708),
        storage_stand=Pose.from_xyz_rpy(1.40, -0.29, 0.0),
        delivery_pose=Pose.from_xyz_rpy(6.75, -1.20, 0.818),
        delivery_stand=Pose.from_xyz_rpy(5.95, -1.44, 0.0),
        # standing upright, so the fingers close on its 0.065 m side
        approach_direction=ApproachDirection.FRONT,
        vertical_alignment=VerticalAlignment.NoAlignment,
        rotate_gripper=False,
    ),
    Part(
        mesh=PartMesh.WRENCH,
        color=Color(0.55, 0.57, 0.60),
        storage_pose=Pose.from_xyz_rpy(2.35, -1.25, 0.716),
        storage_stand=Pose.from_xyz_rpy(1.40, -1.49, 0.0),
        delivery_pose=Pose.from_xyz_rpy(6.75, -1.80, 0.826),
        delivery_stand=Pose.from_xyz_rpy(5.95, -2.04, 0.0),
        # standing upright in a tool rack: the hand comes down onto its head and closes
        # on the 0.009 m web, the only dimension a parallel gripper can span
        approach_direction=ApproachDirection.FRONT,
        vertical_alignment=VerticalAlignment.TOP,
        rotate_gripper=False,
    ),
    Part(
        mesh=PartMesh.AXLE,
        color=Color(0.45, 0.47, 0.50),
        storage_pose=Pose.from_xyz_rpy(2.50, 2.60, 0.693, roll=LYING_ON_ITS_SIDE),
        storage_stand=Pose.from_xyz_rpy(1.55, 2.36, 0.0),
        delivery_pose=Pose.from_xyz_rpy(6.75, -3.20, 0.743, roll=LYING_ON_ITS_SIDE),
        delivery_stand=Pose.from_xyz_rpy(5.95, -3.44, 0.0),
        # lying across the shelf front: the hand comes down along the rack and closes
        # across the 0.025 m rod rather than along its 0.845 m length
        approach_direction=ApproachDirection.LEFT,
        vertical_alignment=VerticalAlignment.NoAlignment,
        rotate_gripper=False,
    ),
    Part(
        mesh=PartMesh.PLATE,
        color=Color(0.72, 0.70, 0.66),
        storage_pose=Pose.from_xyz_rpy(2.50, 3.20, 0.80, roll=LYING_ON_ITS_SIDE),
        # a third of a metre closer in than the other parts are fetched from: the rolled
        # wrist costs reach, and from their distance the arm stalls short of the plate
        storage_stand=Pose.from_xyz_rpy(1.85, 2.96, 0.0),
        delivery_pose=Pose.from_xyz_rpy(6.60, -2.40, 0.83, roll=LYING_ON_ITS_SIDE),
        # squared up on the drop rather than offset to the hand's side like the others,
        # which is the difference between putting the plate down and stalling in front
        # of it
        delivery_stand=Pose.from_xyz_rpy(6.05, -2.40, 0.0),
        # standing on its rim, with the hand rolled a quarter turn so the fingers close
        # on the 0.02 m thickness instead of the 0.2 m the gripper cannot span
        approach_direction=ApproachDirection.FRONT,
        vertical_alignment=VerticalAlignment.NoAlignment,
        rotate_gripper=True,
    ),
)
"""
The parts the run collects, in the order they are fetched.
"""


# %% the demonstration


@dataclass(kw_only=True)
class PartsCollectionDemonstration(RobotDemonstration):
    """
    Collects four parts from two storage racks and delivers them to a third.
    """

    def build_simulated_world(self) -> World:
        return WorldSpecification.from_urdf(
            os.path.join(_WORLDS, ENV_FILE),
            # the hall is drawn by a visual mesh only, and the robot has to bump into it
            collision_defaults_to_visual=True,
            robots=[
                RobotSpecification(
                    semantic_annotation_type=self.used_robot,
                    world_T_odom=HomogeneousTransformationMatrix.from_xyz_rpy(
                        ROBOT_XY[0], ROBOT_XY[1], 0.0
                    ),
                ),
            ],
        ).to_domain_object()

    def is_scene_populated(self, world: World) -> bool:
        present = {body.name.name for body in world.bodies}
        return all(part.mesh in present for part in PARTS)

    def populate_scene(self, world: World) -> None:
        for part in PARTS:
            # a pick-up takes the annotation of what it grasps, not the bare body, so
            # each part is spawned already named by one
            SemanticAnnotationWithRootSpecification(
                part.mesh,
                semantic_annotation_type=HasRootBody,
                # free to move (Connection6DoF), so the robot can pick it up and carry it
                root_specification=BodySpecification.mesh(
                    part.mesh,
                    os.path.join(_OBJECTS, part.mesh),
                    color=part.color,
                    parent_T_self=part.storage_pose.to_homogeneous_matrix(),
                    connection_specification=Connection6DoFSpecification(),
                ),
            ).spawn(world)

    def build_context(self, world: World) -> Context:
        with world.modify_world():
            WorldReasoner(world).reason()
        robot = world.get_semantic_annotations_by_type(self.used_robot)[0]
        if isinstance(robot, HasMobileBase):
            robot.mobile_base.full_body_controlled = BASE_MAY_DRIVE_WHILE_REACHING
        context = Context(
            world=world, robot=robot, _debug=False, ros_node=self.ros_node
        )
        context.evaluate_conditions = False
        return context

    def build_plan(self, context: Context) -> PlanNode:
        world = context.world  # bodies/poses below are resolved against it
        end_effector = ViewManager.get_end_effector_view(CARRYING_ARM, context.robot)
        steps = []
        for part in PARTS:
            steps.extend(
                self.carry(
                    context,
                    self.annotation_of(world, part.mesh),
                    part.grasp(end_effector),
                    part.storage_stand,
                    part.delivery_pose,
                    part.delivery_stand,
                )
            )
        return sequential(steps, context=context).plan

    @staticmethod
    def annotation_of(world: World, mesh: PartMesh) -> HasRootBody:
        """
        The annotation naming one of the collected parts.

        :param world: The world the part was spawned in.
        :param mesh: The mesh the part is made of, which is also its body's name.
        """
        body = world.get_body_by_name(mesh)
        return next(
            annotation
            for annotation in world.get_semantic_annotations_by_type(HasRootBody)
            if annotation.root is body
        )

    def carry(
        self,
        context: Context,
        part: HasRootBody,
        grasp: GraspDescription,
        stand_to_pick: Pose,
        destination: Pose,
        stand_to_place: Pose,
    ) -> list:
        """
        One leg: fetch a part from where it lies and put it down at ``destination``.

        Both base poses are passed in rather than derived, so the same leg carries a
        part back to its rack by swapping them.

        :param context: The plan context the actions are built against.
        :param part: The annotation of the part being carried.
        :param grasp: How the part is taken hold of.
        :param stand_to_pick: Base pose the part is picked up from.
        :param destination: Where the part is put down.
        :param stand_to_place: Base pose the part is put down from.
        """
        return [
            NavigateAction(self.against_world_root(context, stand_to_pick)),
            ParkArmsAction(Arms.BOTH),
            MoveTorsoAction(TorsoState.MID),
            PickUpAction(part, CARRYING_ARM, grasp),
            ParkArmsAction(Arms.BOTH),
            NavigateAction(self.against_world_root(context, stand_to_place)),
            PlaceAction(
                part.root, self.against_world_root(context, destination), CARRYING_ARM
            ),
            ParkArmsAction(Arms.BOTH),
        ]

    @staticmethod
    def against_world_root(context: Context, pose: Pose) -> Pose:
        """
        A pose from this file, expressed in the world it is used in.

        :param context: The plan context holding that world.
        :param pose: The pose to re-reference.
        """
        return Pose(
            pose.to_position(),
            pose.to_quaternion(),
            reference_frame=context.world.root,
        )


def main() -> None:
    """
    Run the demonstration.

    RobotDemonstration.run() acquires the world, starts the visualization backend,
    attaches the plan and performs it. The backend defaults to CRAMERA (the browser
    viewer); CORAPLEX_VISUALIZATION overrides it, so `cramera-live` works unchanged and
    you can also force RVIZ / NONE from the outside.
    """
    PartsCollectionDemonstration(
        used_robot=Garmi,
        collision_avoidance=AVOIDS_COLLISIONS,
        default_visualization_backend=VisualizationBackend.CRAMERA,
    ).run()


if __name__ == "__main__":
    main()
