"""
The Garmi collecting four machine parts from two storage racks onto a delivery rack.

Grown out of a Plan Builder demo: the carrying is spelled out as navigate / pick / place
rather than a TransportAction, because warehouse6 is a single hall mesh with no
navigable floor for a transport's costmap to search.

Every surface used here is one measured off ``warehouse6.glb`` itself, so the parts rest
on the hall's own shelving rather than on furniture spawned beside it. The parts differ
in shape, and so do the grasps: which face the hand closes on is what decides whether a
part fits between the fingers at all.

The screw box keeps the size of ``milk.stl``, so poses captured for that one still fit;
it is generated by ``scripts/make_transport_box_mesh.py``.
"""

from __future__ import annotations

import math
import os
from dataclasses import dataclass
from enum import StrEnum

import numpy as np

from coraplex.datastructures.dataclasses import Context
from coraplex.datastructures.enums import (
    ApproachDirection,
    Arms,
    VerticalAlignment,
    VisualizationBackend,
)
from coraplex.datastructures.grasp import GraspDescription
from coraplex.demonstrations import RobotDemonstration
from coraplex.plans.factories import sequential
from coraplex.plans.plan_node import PlanNode
from coraplex.robot_plans.actions.composite.transporting import TransportAction
from coraplex.view_manager import ViewManager
from semantic_digital_twin.api import (
    BodySpecification,
    Connection6DoFSpecification,
    RobotSpecification,
    SemanticAnnotationWithRootSpecification,
    WorldSpecification,
)
from semantic_digital_twin.collision_checking.collision_rules import (
    AllowCollisionBetweenGroups,
)
from semantic_digital_twin.reasoning.world_reasoner import WorldReasoner
from semantic_digital_twin.robots.garmi import Garmi
from semantic_digital_twin.robots.robot_part_mixins import HasMobileBase
from semantic_digital_twin.robots.robot_parts import EndEffector
from semantic_digital_twin.semantic_annotations.mixins import HasRootBody
from semantic_digital_twin.spatial_types import HomogeneousTransformationMatrix
from semantic_digital_twin.spatial_types.spatial_types import Pose
from semantic_digital_twin.world import World
from semantic_digital_twin.world_description.geometry import Color, Mesh

_HERE = os.path.dirname(__file__)
_OBJECTS = os.path.join(_HERE, "..", "..", "resources", "objects")

GROUND_MODEL = "aws_robomaker_warehouse_GroundB_01"
"""
The model whose mesh is the hall floor, which the robot drives on rather than avoids.
"""

ENV_URI = (
    "package://aws_robomaker_small_warehouse_world/worlds/no_roof_small_warehouse/"
    "no_roof_small_warehouse.world"
)
"""
The warehouse the run takes place in, the same one the Unitree G1 demo uses.

Needs the ``aws_robomaker_small_warehouse_world`` package built in the workspace, since
the world and its meshes are read from its share directory. Every fitting in it is a
body of its own with its own collision geometry, so the aisles stay free of the robot.
"""

FLOOR_TOP = 0.034
"""
Where the warehouse's floor surface sits.

The robot's own frame has its wheels at zero, so its odom is lifted by this much for it
to stand on the floor rather than in it.
"""

STORAGE_TOP = 0.72
"""
Height of the flat top the parts are picked from.

Cast onto the drawn surface rather than taken from the stack's overall height: these
stacks are modelled as uneven piles, so their bounding box tops 20 cm above the only
part of them a thing can be set down on.
"""

STANDING_DISTANCE = 1
"""
How far the robot's base stands from a part it reaches for.

Set by the aisle rather than by the arm: a stack's collision geometry reaches out to
2.324 at the height of the base while its flat top only begins at 2.60, so the base
keeps its distance from the pile and the arm covers the rest.
"""

ROBOT_XY = (0.75, 6.0)
"""
Where the robot starts, in the open aisle between the two stacks it works at.
"""

BASE_MAY_DRIVE_WHILE_REACHING = False
"""
Whether the base may drive to help an arm reach (whole-body control).

Off, because every base pose in this plan is one that was captured deliberately: with it
on, a reach drives the base past the object and into the shelving.
"""

CARRYING_ARM = Arms.LEFT
"""
The arm that picks and places, one hand throughout.
"""

TICKS_PER_MOTION = 6000
"""
How long each motion may take before the run gives up on it.

Three times the default: a motion that has to hold itself off the shelving converges
more slowly than one that may drive straight at its goal, and the run is otherwise given
up on while it is still closing in.
"""

AVOIDS_COLLISIONS = True
"""
Whether every motion of the run carries a collision-avoidance goal.

On, because the hall is collided with: the racks the arm reaches into are geometry the
motions have to be held off, not just scenery the captured poses happen to miss.
"""

LYING_ON_ITS_SIDE = math.pi / 2
"""
Roll that tips a part off its own z-axis onto that axis' side.

It lays the axle down across the shelf front, and stands the plate on its rim.
"""

# %% the parts and where they belong


class PartMesh(StrEnum):
    """
    Mesh file of each part that is collected, which is also the body's name in the
    world.
    """

    SCREW_BOX = "screw_box.obj"
    WRENCH = "wrench.stl"
    AXLE = "axle.stl"
    PLATE = "plate.stl"


@dataclass(frozen=True)
class Part:
    """
    One part of the collection: what it is, where it lies, where it goes, and how the
    hand has to be turned to take hold of it.
    """

    mesh: PartMesh
    """
    The mesh the part is made of.
    """

    color: Color
    """
    What the part is painted, since an STL carries no color of its own.
    """

    storage_pose: Pose
    """
    Where the part lies on the storage rack at the start of the run.
    """

    storage_stand: Pose
    """
    Base pose the robot reaches :attr:`storage_pose` from.
    """

    delivery_pose: Pose
    """
    Where the part is put down on the delivery rack.

    Turned to face the robot, which stands on the opposite side of this stack from the
    one it picks at, so the part is put down from the front rather than reached around.
    """

    delivery_stand: Pose
    """
    Base pose the robot reaches :attr:`delivery_pose` from.
    """

    approach_direction: ApproachDirection
    """
    The side of the part the hand comes in from, in the part's own frame.
    """

    vertical_alignment: VerticalAlignment
    """
    Whether the hand comes down onto the part from above rather than in level with it.
    """

    rotate_gripper: bool
    """
    Whether the hand is rolled a quarter turn about its approach axis, which swaps the
    two faces the fingers can close on.
    """

    def grasp(self, end_effector: EndEffector) -> GraspDescription:
        """
        How this part is taken hold of.

        :param end_effector: The hand doing the grasping.
        """
        return GraspDescription(
            self.approach_direction,
            self.vertical_alignment,
            end_effector,
            rotate_gripper=self.rotate_gripper,
        )


STORAGE_X = -0.75
"""
Where a part rests on the storage stack.

On the very lip of its flat top, which the stack is drawn with from 2.52 and collides
from 2.47: a part further in puts the wrist behind the hand over the higher of those
two, where it is held its buffer distance off the stack and the hand never reaches down.
"""

WRENCH_SHELF = 1.084
"""
The flat top the wrench is taken from, which is a different pile from the one the parcel
rests on and so a different height.
"""

LOWER_PLATEAU = 0.727
"""
The step of the storage stack the parcel is set down on, below the one it is taken from.
"""

CONTAINER_FLOOR = 0.55
"""
Inside of the container the wrench is delivered into.

Its floor runs from 0.50 to 1.00 across and 8.55 to 8.95 along, well below the rim at
1.41, so the hand comes down into it rather than in from the side.
"""

PARTS = (
    Part(
        mesh=PartMesh.SCREW_BOX,
        color=Color(),
        storage_pose=Pose.from_xyz_rpy(STORAGE_X, 5.80, STORAGE_TOP + 0.088, yaw=np.pi),
        storage_stand=Pose.from_xyz_rpy(
            STORAGE_X + STANDING_DISTANCE, 5.80, 0.0, yaw=np.pi
        ),
        delivery_pose=Pose.from_xyz_rpy(2.60, 7.85, LOWER_PLATEAU + 0.088),
        delivery_stand=Pose.from_xyz_rpy(2.60 - STANDING_DISTANCE, 7.85, 0.0),
        # standing upright, so the fingers close on its 0.065 m side
        approach_direction=ApproachDirection.FRONT,
        vertical_alignment=VerticalAlignment.NoAlignment,
        rotate_gripper=False,
    ),
    Part(
        mesh=PartMesh.WRENCH,
        color=Color(0.55, 0.57, 0.60),
        storage_pose=Pose.from_xyz_rpy(
            2.64, 8.65, WRENCH_SHELF - 0.007, roll=LYING_ON_ITS_SIDE
        ),
        storage_stand=Pose.from_xyz_rpy(2.64 - 0.85, 8.65, 0.0),
        delivery_pose=Pose.from_xyz_rpy(
            0.9, 8.3, CONTAINER_FLOOR - 0.007, roll=LYING_ON_ITS_SIDE, yaw=-math.pi / 2
        ),
        delivery_stand=Pose.from_xyz_rpy(0.72, 7.55, 0.0, yaw=math.pi / 2),
        # lying flat and taken from above, since it is delivered into a container whose
        # walls leave no way in from the side. Flat rather than standing, because a hand
        # descending on a wrench stood on end brings the wrist down beside it, and the
        # arm is held its buffer distance clear of whatever it reaches for.
        approach_direction=ApproachDirection.LEFT,
        vertical_alignment=VerticalAlignment.NoAlignment,
        rotate_gripper=False,
    ),
    # Part(
    #     mesh=PartMesh.AXLE,
    #     color=Color(0.45, 0.47, 0.50),
    #     storage_pose=Pose.from_xyz_rpy(2.50, 2.60, 0.693, roll=LYING_ON_ITS_SIDE),
    #     storage_stand=Pose.from_xyz_rpy(1.55, 2.36, 0.0),
    #     delivery_pose=Pose.from_xyz_rpy(6.75, -3.20, 0.743, roll=LYING_ON_ITS_SIDE),
    #     delivery_stand=Pose.from_xyz_rpy(5.95, -3.44, 0.0),
    #     # lying across the shelf front: the hand comes down along the rack and closes
    #     # across the 0.025 m rod rather than along its 0.845 m length
    #     approach_direction=ApproachDirection.LEFT,
    #     vertical_alignment=VerticalAlignment.NoAlignment,
    #     rotate_gripper=False,
    # ),
    # Part(
    #     mesh=PartMesh.PLATE,
    #     color=Color(0.72, 0.70, 0.66),
    #     storage_pose=Pose.from_xyz_rpy(2.50, 3.20, 0.80, roll=LYING_ON_ITS_SIDE),
    #     # a third of a metre closer in than the other parts are fetched from: the rolled
    #     # wrist costs reach, and from their distance the arm stalls short of the plate
    #     storage_stand=Pose.from_xyz_rpy(1.85, 2.96, 0.0),
    #     delivery_pose=Pose.from_xyz_rpy(6.60, -2.40, 0.83, roll=LYING_ON_ITS_SIDE),
    #     # squared up on the drop rather than offset to the hand's side like the others,
    #     # which is the difference between putting the plate down and stalling in front
    #     # of it
    #     delivery_stand=Pose.from_xyz_rpy(6.05, -2.40, 0.0),
    #     # standing on its rim, with the hand rolled a quarter turn so the fingers close
    #     # on the 0.02 m thickness instead of the 0.2 m the gripper cannot span
    #     approach_direction=ApproachDirection.FRONT,
    #     vertical_alignment=VerticalAlignment.NoAlignment,
    #     rotate_gripper=True,
    # ),
)
"""
The parts the run collects, in the order they are fetched.

The axle and the plate are left out of the run: the flat tops of these two stacks
measure 0.5 m at their longest, so the 0.845 m axle rests on neither of them, and the
plate is 0.2 m across, which puts the wrist carrying the hand inside the distance the
arm is held off whatever it reaches for whichever side it is approached from.
"""


# %% the demonstration


@dataclass(kw_only=True)
class PartsCollectionDemonstration(RobotDemonstration):
    """
    Collects four parts from two storage racks and delivers them to a third.
    """

    def build_simulated_world(self) -> World:
        world = self._hall_with_the_robot_in_it()
        self._let_the_base_rest_on_the_floor(world)
        return world

    @staticmethod
    def _let_the_base_rest_on_the_floor(world: World) -> None:
        """
        Stop the floor being an obstacle to the base that drives on it.

        A robot on wheels rests on the floor, so its base touches it wherever it stands
        and every pose it could be sent to counts as a collision otherwise. Only the
        base is freed; an arm still has to stay off the floor.

        :param world: The world holding the hall and the robot.
        """
        ground = [
            body
            for body in world.bodies
            if any(
                isinstance(shape, Mesh) and GROUND_MODEL in shape.filename
                for shape in body.collision
            )
        ]
        robot = world.get_semantic_annotations_by_type(Garmi)[0]
        with world.modify_world():
            world.collision_manager.add_ignore_collision_rule(
                AllowCollisionBetweenGroups(
                    body_group_a=ground,
                    body_group_b=list(robot.mobile_base.bodies_with_collision),
                )
            )

    def _hall_with_the_robot_in_it(self) -> World:
        """
        :return: The warehouse with the robot standing in its aisle.
        """
        return WorldSpecification.from_gazebo(
            ENV_URI,
            # The hall collides as a handful of boxes standing in for shapes drawn in
            # far more detail, which buries every ledge below a pile's top in solid
            # geometry. Colliding as it is drawn gives the decomposition the real shape.
            collision_from_visual=True,
            robots=[
                RobotSpecification(
                    semantic_annotation_type=self.used_robot,
                    world_T_odom=HomogeneousTransformationMatrix.from_xyz_rpy(
                        ROBOT_XY[0], ROBOT_XY[1], FLOOR_TOP
                    ),
                ),
            ],
        ).to_domain_object()

    def is_scene_populated(self, world: World) -> bool:
        present = {body.name.name for body in world.bodies}
        return all(part.mesh in present for part in PARTS)

    def populate_scene(self, world: World) -> None:
        for part in PARTS:
            # a pick-up takes the annotation of what it grasps, not the bare body, so
            # each part is spawned already named by one
            SemanticAnnotationWithRootSpecification(
                part.mesh,
                semantic_annotation_type=HasRootBody,
                # free to move (Connection6DoF), so the robot can pick it up and carry it
                root_specification=BodySpecification.mesh(
                    part.mesh,
                    os.path.join(_OBJECTS, part.mesh),
                    color=part.color,
                    parent_T_self=part.storage_pose.to_homogeneous_matrix(),
                    connection_specification=Connection6DoFSpecification(),
                ),
            ).spawn(world)

    def build_context(self, world: World) -> Context:
        with world.modify_world():
            WorldReasoner(world).reason()
        robot = world.get_semantic_annotations_by_type(self.used_robot)[0]
        # if isinstance(robot, HasMobileBase):
        #     robot.mobile_base.full_body_controlled = BASE_MAY_DRIVE_WHILE_REACHING
        context = Context(
            world=world,
            robot=robot,
            _debug=True,
            ros_node=self.ros_node,
            ticks_per_motion=TICKS_PER_MOTION,
        )
        context.evaluate_conditions = False
        return context

    def build_plan(self, context: Context) -> PlanNode:
        world = context.world  # bodies/poses below are resolved against it
        end_effector = ViewManager.get_end_effector_view(CARRYING_ARM, context.robot)
        steps = [
            self.carry(
                context,
                self.annotation_of(world, part.mesh),
                part.grasp(end_effector),
                part.delivery_pose,
            )
            for part in PARTS
        ]
        return sequential(steps, context=context).plan

    @staticmethod
    def annotation_of(world: World, mesh: PartMesh) -> HasRootBody:
        """
        The annotation naming one of the collected parts.

        :param world: The world the part was spawned in.
        :param mesh: The mesh the part is made of, which is also its body's name.
        """
        body = world.get_body_by_name(mesh)
        return next(
            annotation
            for annotation in world.get_semantic_annotations_by_type(HasRootBody)
            if annotation.root is body
        )

    def carry(
        self,
        context: Context,
        part: HasRootBody,
        grasp: GraspDescription,
        destination: Pose,
    ) -> TransportAction:
        """
        One leg: fetch a part from where it lies and put it down at ``destination``.

        The base pose for either end is left to the transport, which searches the floor
        around the part and around where it is going for somewhere the arm reaches from.

        :param context: The plan context the action is built against.
        :param part: The annotation of the part being carried.
        :param grasp: How the part is taken hold of.
        :param destination: Where the part is put down.
        """
        return TransportAction(
            object_designator=part,
            target_location=self.against_world_root(context, destination),
            arm=CARRYING_ARM,
            grasp_description=grasp,
        )

    @staticmethod
    def against_world_root(context: Context, pose: Pose) -> Pose:
        """
        A pose from this file, expressed in the world it is used in.

        :param context: The plan context holding that world.
        :param pose: The pose to re-reference.
        """
        return Pose(
            pose.to_position(),
            pose.to_quaternion(),
            reference_frame=context.world.root,
        )


def main() -> None:
    """
    Run the demonstration.

    RobotDemonstration.run() acquires the world, starts the visualization backend,
    attaches the plan and performs it. The backend defaults to CRAMERA (the browser
    viewer); CORAPLEX_VISUALIZATION overrides it, so `cramera-live` works unchanged and
    you can also force RVIZ / NONE from the outside.
    """
    PartsCollectionDemonstration(
        used_robot=Garmi,
        collision_avoidance=AVOIDS_COLLISIONS,
        # default_visualization_backend=VisualizationBackend.CRAMERA,
    ).run()


if __name__ == "__main__":
    main()
